kind: PersistentVolume
apiVersion: v1
metadata:
  name: reg-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/efs"
