apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-registry-tls
  labels:
    service: registry-service
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: registry-selector
    spec:
      containers:
      - name: registry-tls
        image: registry:latest
          # keep request = limit to keep this container in guaranteed class
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_HTTP_SECRET
          value: "5994040113136112"
        - name: REGISTRY_LOG_LEVEL
          value: info
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR
          value: redis
        - name: REGISTRY_REDIS_ADDR
          value: redis-cache:6379
        - name: REGISTRY_REDIS_DIALTIMEOUT
          value: 10ms
        - name: REGISTRY_REDIS_READTIMEOUT
          value: 10ms
        - name: REGISTRY_REDIS_WRITETIMEOUT
          value: 10ms
        - name: REGISTRY_REDIS_POOL_MAXIDLE
          value: "16"
        - name: REGISTRY_REDIS_POOL_MAXACTIVE
          value: "64"
        - name: REGISTRY_REDIS_POOL_IDLETIMEOUT
          value: 300s
        volumeMounts:
        - name: image-store
          mountPath: /var/lib/registry
        ports:
        - containerPort: 5000
          name: registry-tls
          protocol: TCP
      - name: registry-tls-ui
        image: konradkleine/docker-registry-frontend:v2
        env:
        - name: ENV_DOCKER_REGISTRY_HOST
          value: "localhost"
        - name: ENV_DOCKER_REGISTRY_PORT
          value: "5000"
        ports:
        - containerPort: 80
          name: registry-tls-ui
          protocol: TCP
      volumes:
      - name: image-store
        persistentVolumeClaim:
          claimName: reg-pv-claim
