apiVersion: v1
kind: Service
metadata:
  name: redis-cache
  labels:
    name: redis-cache
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-selector

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-cache-deployment
  labels:
    service: redis-cache
  annotations:
    security.alpha.kubernetes.io/sysctls: net.core.somaxconn=262144
spec:
  # https://github.com/kubernetes/kubernetes/issues/23597
  revisionHistoryLimit: 3
  replicas: 1
  template:
    metadata:
      labels:
        name: redis-selector
    spec:
      containers:
      - name: redis
        image: redis:3
        securityContext:
            privileged: true
        ports:
         - containerPort: 6379
        volumeMounts:
         - name: redis-config
           mountPath: /etc/redis
         - name: redis-store
           mountPath: /var/lib/redis
      volumes:
      - name: redis-store
        emptyDir: {}
      - name: redis-config
        emptyDir: {}
