apiVersion: v1
kind: ConfigMap
data:
  proxy-body-size: "0"
  proxy-read-timeout: "900" 
  client-body-buffer-size: "2000m"
  chunked-transfer-encoding: "on"
  lb-method: "ip_hash"
metadata:
  name: nginx
  labels:
    k8s-app: nginx-ingress-lb
  namespace: nginx-ingress
